name: tool
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.0
  collection: ^1.16.0
  shared:
    path: ../shared
  path: ^1.8.0
  pubspec_parse: ^1.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  lotum_analysis:
    git:
      url: https://github.com/lotum/lotum_analysis.git
      ref: lotum_analysis-v1.0.2

dependency_overrides:
  soundpool_platform_interface:
    git:
      url: https://github.com/lotum/soundpool.git
      ref: 9fd95cde1dd5782bf7c7cbadcb16eb007e684026
      path: soundpool_platform_interface
  soundpool_web:
    git:
      url: https://github.com/lotum/soundpool.git
      ref: 9fd95cde1dd5782bf7c7cbadcb16eb007e684026
      path: soundpool_web

